version: '3.8'

services:
  rag-app:
    build: .
    volumes:
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  ollama_data:
